version: '2'
services:
    pharmarket-app:
        image: pharmarket
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pharmarket-mysql:3306/pharmarket?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pharmarket-mysql:
        extends:
            file: mysql.yml
            service: pharmarket-mysql
